# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

source 'https://cdn.cocoapods.org/'
#source "git@github.com:JetBrains/kotlin-native-cocoapods.git"

project 'iosApp.xcodeproj'

target 'iosApp' do
    platform :ios, '15.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'composeApp', :path => '../composeApp' 

end